openapi: 3.0.0
x-stoplight:
  id: kqqn8yroahnx7
info:
  title: Test
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /point-to-point:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-point-to-point
      x-stoplight:
        id: eie6rc7r6wu04
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
components:
  schemas:
    Leg:
      title: Leg
      x-stoplight:
        id: ociuxu82ahr68
      type: object
      properties:
        carrierServiceName:
          type: string
          x-stoplight:
            id: fxsfv7fk6dd1b
        carrierServiceCode:
          type: string
          x-stoplight:
            id: h3jzg790rqeg2
        modeOfTransportType:
          x-stoplight:
            id: a0pus0r5yob6i
          description: "Defines the mode of Transport. The allowed values are:\r\n- VESSEL\r\n- RAIL\r\n- BARGE\r\n- TRUCK\r\n- RAILORTRUCK\r\n- BARGEORTRUCK\r\n- RAILORBARGE\r\n- MULTIMODAL"
          type: string
          example: VESSEL
        modeOfTransport:
          x-stoplight:
            id: bwvcir8df4lbw
          oneOf:
            - $ref: '#/components/schemas/Rail'
            - $ref: '#/components/schemas/Vessel'
            - $ref: '#/components/schemas/Truck'
            - $ref: '#/components/schemas/Barge'
            - $ref: '#/components/schemas/Combined'
          description: "The mode of Transport. Depending upon the mode of transport type the data will be different.\r\n\r\nCondition : If the modeOfTransport type is combined modes then the modeOfTransport will not have specific data."
    Barge:
      title: Barge
      x-stoplight:
        id: t8fw3u6u9006m
      type: object
      properties:
        flag:
          type: string
          x-stoplight:
            id: 7oi4ziz3n8g0t
        callSign:
          type: string
          x-stoplight:
            id: d7r9u0crln0p3
    Vessel:
      title: Vessel
      x-stoplight:
        id: 54wo9l8pmln4n
      type: object
      properties:
        vesselIMONumber:
          type: string
          x-stoplight:
            id: ifl0d5bzmxsp0
        vesselName:
          type: string
          x-stoplight:
            id: crqdu70bed7hg
        vesselOperatorCarrierCode:
          type: string
          x-stoplight:
            id: 1gtr4w47tq9rq
    Rail:
      title: Rail
      x-stoplight:
        id: di9eaddxz5d9p
      type: object
      properties:
        railservice:
          type: string
          x-stoplight:
            id: 10kfncx6h6knn
        railcar:
          type: string
          x-stoplight:
            id: 12ikpcm2mf51v
    Multimodal:
      title: Multimodal
      x-stoplight:
        id: few9d3g3o1lyv
      type: object
      properties:
        id:
          type: string
          x-stoplight:
            id: e6ecfndldvoyy
    RailOrTruck:
      title: RailOrTruck
      x-stoplight:
        id: 03bunp1aegqun
      type: object
      properties:
        railCar:
          type: string
          x-stoplight:
            id: kk6iswbahfjv4
        railService:
          type: string
          x-stoplight:
            id: vxiylqaon8gtv
        licensePlate:
          type: string
          x-stoplight:
            id: du04ci49f45yp
        chasisLicensePlate:
          type: string
          x-stoplight:
            id: q6q5a3ayz5m2v
    BargeOrTruck:
      title: BargeOrTruck
      x-stoplight:
        id: lmhtduepfk7oe
      type: object
      properties:
        flag:
          type: string
          x-stoplight:
            id: 3ijtiae8c9uzq
        callSign:
          type: string
          x-stoplight:
            id: kv1kpn616h4am
        licensePlate:
          type: string
          x-stoplight:
            id: fql5nvuqtx5qv
        chasisLicensePlate:
          type: string
          x-stoplight:
            id: f47xjibzrq7lr
        '':
          type: string
          x-stoplight:
            id: 6n4spgd81zewk
    RailOrBarge:
      title: RailOrBarge
      x-stoplight:
        id: uiwbawy1q4h2d
      type: object
      properties:
        railService:
          type: string
          x-stoplight:
            id: jnre0l7cekt3v
        railCar:
          type: string
          x-stoplight:
            id: 6jlibpfns9vm3
        flag:
          type: string
          x-stoplight:
            id: hmip365jze9c1
        departureID:
          type: string
          x-stoplight:
            id: njv8ycjj6mdt1
        callSign:
          type: string
          x-stoplight:
            id: 0sej94gnp2wuo
        '':
          type: string
          x-stoplight:
            id: so2cxuz973727
    Truck:
      title: Truck
      x-stoplight:
        id: hrfdw6v923yjz
      type: object
      properties:
        licensePlate:
          type: string
          x-stoplight:
            id: h8eurfexs3qwh
        chasisLicensePlate:
          type: string
          x-stoplight:
            id: pf7ckvgyr9x8j
        '':
          type: string
          x-stoplight:
            id: 1xkkpz4tfpwx7
    Combined:
      title: EmptySchema
      x-stoplight:
        id: bnwqijme1s8an
      type: object
