openapi: 3.1.0
x-stoplight:
  id: htyyc9fjsgqde
info:
  title: DCSA Components
  description: |
    Common header components for DCSA APIs.
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  contact:
    name: Digital Container Shipping Association (DCSA)
    url: 'https://dcsa.org'
    email: info@dcsa.org
  version: ''
components:
  headers:
    API-Version:
      schema:
        type: string
        example: '1.0.0'
      description: |
        SemVer used to indicate the version of the contract (API version) returned.
  parameters:
    APIVersionMajor:
      name: API-Version
      in: header
      description: An API-Version header **MAY** be added to the request (optional); if added it **MUST** only contain **MAJOR** version. API-Version header **MUST** be aligned with the URI version.
      schema:
        type: string
        example: '1'
    Limit:
      name: limit
      in: query
      description: Maximum number of items to return.
      schema:
        type: number
        minimum: 0
        default: 100
